PUT http://localhost:8080/users/1
content-type: application/json

{
        "id": 1,
        "username": "lumpen422",
        "email": "test@rest.com",
        "password": "1234",
        "userRole": {
          "rolename": "admin"
        },
        "_links": {
          "self": {
            "href": "http://localhost:8080/users/1"
          },
          "user": {
            "href": "http://localhost:8080/users/1"
          }
        }
}


$ curl -X PUT -H "Content-Type: application/json" -d '{"id": 1, "username": "lumpen422", "email": "test@rest.com", "password": "1234","userRole": {"rolename": "admin"},"_links": {"self": {"href": "http://localhost:8080/users/1"}, "user": {"href": "http://localhost:8080/users/1"}}}' http://localhost:8080/users/1